### ISSUE TITLE
--ext-code-file doesn't accept jsonnet

### ISSUE THREAD

**Issue by akursell-wish** [databricks/sjsonnet#47]
Using either `jsonnet` or `go-jsonnet`, a `.jsonnet` file can be passed as an `extVar` using `--ext-code-file`. It looks like `sjsonnet` only accepts JSON, not jsonnet passed using `--ext-code-file`.

```shell 
$ cat ext.jsonnet
{
  foo: "world",
}
$ cat foo.jsonnet
local ext = std.extVar("ext");
{
  hello: ext.foo,
}
$ jsonnet --ext-code-file ext=./ext.jsonnet ./foo.jsonnet
{
   "hello": "world"
}
$ sjsonnet --ext-code-file ext=./ext.jsonnet ./foo.jsonnet
Exception in thread "main" ujson.ParseException: expected " got f (line 2, column 5) at index 4
        at ujson.Parser.die(Parser.scala:109)
        at ujson.Parser.rparse(Parser.scala:459)
        at ujson.Parser.parse(Parser.scala:331)
        at ujson.SyncParser.parse(SyncParser.scala:23)
        at ujson.StringParser$.transform(StringParser.scala:30)
        at ujson.StringParser$.transform(StringParser.scala:29)
        at ujson.Readable$fromTransformer.transform(Readable.scala:13)
        at ujson.package$.transform(package.scala:4)
        at ujson.package$.read(package.scala:9)
        at sjsonnet.Cli$.$anonfun$genericSignature$11(Cli.scala:90)
        at sjsonnet.Cli$Arg.runAction(Cli.scala:12)
        at sjsonnet.Cli$.rec$1(Cli.scala:167)
        at sjsonnet.Cli$.groupArgs(Cli.scala:178)
        at sjsonnet.SjsonnetMain$.main0(SjsonnetMain.scala:51)
        at sjsonnet.SjsonnetMain$.main(SjsonnetMain.scala:26)
        at sjsonnet.SjsonnetMain.main(SjsonnetMain.scala)
```

**Comment by kuparek** [comment]
Hey, any updates on if/when this is going to get fixed? Thanks!
